// frontend/app/components/Contact.tsx
'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { submitContact } from '@/app/actions/contact'

interface ContactFormData {
  firstName: string
  lastName: string
  email: string
  phone: string
  message: string
}

const inputClass =
  'font-[inherit] text-[1.2rem] md:text-[1.625rem] border-0 outline-0 w-full rounded-[3px] transition-all duration-300 text-primary bg-footer-dark mb-[2.1875rem] p-5 placeholder:text-center placeholder:font-black placeholder:text-primary focus:outline-none overflow-hidden'

const errorClass =
  'absolute text-[0.7rem] mt-[-1.65rem] left-1/2 -translate-x-1/2 text-red-400 whitespace-nowrap'

export function Contact() {
  const [submitted, setSubmitted] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting, isValid },
    reset,
  } = useForm<ContactFormData>({ mode: 'onTouched' })

  const onSubmit = async (data: ContactFormData) => {
    setSubmitError(null)
    const result = await submitContact(data)
    if (result.success) {
      setSubmitted(true)
      reset()
      setTimeout(() => setSubmitted(false), 5000)
    } else {
      setSubmitError(result.error || 'Nachricht konnte nicht gesendet werden.')
    }
  }

  return (
    <section id="contact-form" className="bg-footer-light text-text-light text-center font-bold">
      <div className="w-full max-w-[78rem] mx-auto px-[1.3rem] py-[3.25rem] md:py-[5rem] desktop:px-0 relative">
        <h2 className="text-[1.65rem] md:text-[3rem] font-bold mb-0">Kontaktieren Sie uns...</h2>

        <div className="text-[0.75rem] md:px-32 mt-0">
          <p className="leading-normal my-4">
            Hinterlassen Sie mir eine Nachricht und ich nehme gerne Kontakt zu Ihnen auf.
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="pt-[3.9rem] md:pt-[5.375rem]">
          <div className="relative">
            <input
              type="text"
              placeholder="Vorname eingeben"
              {...register('firstName', { required: 'Bitte geben Sie Ihren Vornamen ein' })}
              className={inputClass}
            />
            {errors.firstName && (
              <p className={errorClass}>{errors.firstName.message}</p>
            )}
          </div>

          <div className="relative">
            <input
              type="text"
              placeholder="Nachname eingeben"
              {...register('lastName', { required: 'Bitte geben Sie Ihren Nachnamen ein' })}
              className={inputClass}
            />
            {errors.lastName && (
              <p className={errorClass}>{errors.lastName.message}</p>
            )}
          </div>

          <div className="relative">
            <input
              type="email"
              placeholder="eMail-Adresse eingeben"
              {...register('email', {
                required: 'Bitte geben Sie eine gültige eMail-Adresse ein',
                pattern: {
                  value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                  message: 'Bitte geben Sie eine gültige eMail-Adresse ein',
                },
              })}
              className={inputClass}
            />
            {errors.email && (
              <p className={errorClass}>{errors.email.message}</p>
            )}
          </div>

          <div className="relative">
            <input
              type="tel"
              placeholder="Telefonnummer eingeben"
              {...register('phone', { required: 'Bitte geben Sie eine gültige Telefonnummer ein' })}
              className={inputClass}
            />
            {errors.phone && (
              <p className={errorClass}>{errors.phone.message}</p>
            )}
          </div>

          <div className="relative">
            <textarea
              placeholder="Ihre Nachricht"
              {...register('message', { required: 'Bitte geben Sie eine Nachricht ein' })}
              className="font-[inherit] text-[1.2rem] md:text-[1.625rem] border-0 outline-0 w-full rounded-[3px] transition-all duration-300 text-primary bg-footer-dark mb-[2.1875rem] p-5 desktop:py-[1.875rem] placeholder:text-center placeholder:font-bold placeholder:leading-[6rem] placeholder:text-primary min-h-[10.5rem] resize-none overflow-auto focus:outline-none"
            />
            {errors.message && (
              <p className={errorClass}>{errors.message.message}</p>
            )}
          </div>

          {submitError && (
            <p className="text-red-400 text-[0.8rem] mb-4">{submitError}</p>
          )}

          <div>
            <button
              type="submit"
              disabled={isSubmitting || !isValid}
              className="text-[1rem] md:text-[1.325rem] block w-[30%] min-w-[18.75rem] border-0 p-0 leading-[3em] bg-tertiary text-text-gray lowercase text-center mx-auto cursor-pointer transition-all duration-200 hover:bg-primary disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isSubmitting ? 'Wird gesendet...' : 'Absenden'}
            </button>
          </div>
        </form>

        {submitted && (
          <div className="max-w-[50%] p-4 absolute left-1/2 -translate-x-1/2 text-text-light font-semibold">
            Danke für Ihre Nachricht, ich komme so schnell wie möglich auf Sie zu.
          </div>
        )}
      </div>
    </section>
  )
}

// menntec/src/app/components/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, NgForm, Validators } from '@angular/forms';
import { Apollo } from 'apollo-angular';
import { INQUIRIES_MUTATION } from '../../apollo/queries';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.sass'],
})
export class ContactComponent implements OnInit {
  submitted = false;
  contactData: any = {};

  constructor(private apollo: Apollo) {}

  ngOnInit(): void {}

  // Submit Contact Form

  // tslint:disable-next-line: typedef
  onSubmit(form: NgForm) {
    this.submitted = true;

    this.apollo
      .mutate({
        mutation: INQUIRIES_MUTATION,
        variables: {
          firstName: this.contactData.firstName,
          lastName: this.contactData.lastName,
          phone: this.contactData.tel,
          email: this.contactData.eMail,
          message: this.contactData.message,
        },
      })
      // tslint:disable-next-line: deprecation
      .subscribe(
        ({ data }) => {},
        (error) => {
          console.log(error);
        }
      );

    form.reset();
    this.resetSubmit();
  }

  // tslint:disable-next-line: typedef
  resetSubmit() {
    setTimeout(() => {
      this.submitted = false;
    }, 5000);
  }
}

<section id="contact-form" class="contact dark_bg txt-lght center">
  <div class="contact__container inner bold">
    <h2 class="contact__title">Kontaktieren Sie uns...</h2>
    <div class="contact__description">
      <p class="contact__text">
        Sie suchen einen Partner für Ihr nächstes Projekt? Hinterlassen Sie mir
        eine Nachricht und nehme gerne Kontakt zu Ihnen auf.
      </p>
    </div>

    <div class="contact__form">
      <form
        (ngSubmit)="onSubmit(contForm)"
        #form="ngForm"
        #contForm="ngForm"
        novalidate
      >
        <div class="inputField">
          <input
            type="text"
            name="firstName"
            class="contact__form__input"
            placeholder="Vorname eingeben"
            [(ngModel)]="contactData.firstName"
            #firstNameInput="ngModel"
            required
          />
          <div
            class="is-error"
            *ngIf="firstNameInput.invalid && firstNameInput.touched"
          >
            Bitte geben Sie Ihren Vornamen ein
          </div>
        </div>
        <div class="inputField">
          <input
            type="text"
            name="lastName"
            class="contact__form__input"
            placeholder="Nachname eingeben"
            [(ngModel)]="contactData.lastName"
            #lastNameInput="ngModel"
            required
          />
          <div
            class="is-error"
            *ngIf="lastNameInput.invalid && lastNameInput.touched"
          >
            Bitte geben Sie Ihren Nachnamen ein
          </div>
        </div>
        <div class="inputField">
          <input
            type="email"
            name="eMail"
            class="contact__form__input"
            placeholder="eMail-Adresse eingeben"
            [(ngModel)]="contactData.eMail"
            #eMailInput="ngModel"
            email
            required
          />
          <div
            class="is-error"
            *ngIf="eMailInput.invalid && eMailInput.touched"
          >
            Bitte geben Sie eine gültige eMail-Adresse ein
          </div>
        </div>
        <div class="inputField">
          <input
            type="tel"
            name="tel"
            class="contact__form__input"
            placeholder="Telefonnummer eingeben"
            [(ngModel)]="contactData.tel"
            #telInput="ngModel"
            number
            required
          />
          <div class="is-error" *ngIf="telInput.invalid && telInput.touched">
            Bitte geben Sie eine gültige Telefonnumer ein
          </div>
        </div>
        <div class="inputField">
          <textarea
            name="message"
            placeholder="Ihre Nachricht"
            class="contact__form__input text"
            [(ngModel)]="contactData.message"
            #messageInput="ngModel"
            required
          ></textarea>
          <div
            class="is-error"
            *ngIf="messageInput.invalid && messageInput.touched"
          >
            Bitte geben Sie eine Nachricht ein
          </div>
        </div>
        <div>
          <button
            type="submit"
            class="btn btn-primary btn-cf bold txt-gray"
            [disabled]="contForm.invalid"
          >
            Absenden
          </button>
        </div>
      </form>
    </div>
    <div class="contact__sent" *ngIf="submitted">
      Danke für Ihre Nachricht, ich komme so schnell wie möglich auf Sie zu.
    </div>
  </div>
</section>
